class Dictionary:
    def __new__(
        config_str: str, dict_str: str, personal_str: str | None
    ) -> Dictionary: ...
    def check(self, input: str) -> bool: ...
    def check_word(self, word: str) -> bool: ...

class BuildError: ...
class IoError: ...
class ParseError: ...
class RegexError: ...
