// autogenerated file, do not edit manually
//! Runner for the `.test` integration test format
#![cfg_attr(rustfmt, rustfmt_skip)] // FIXME: generate these in `OUTPUT_DIR` rather than `src`

use test_util::TestManager;

#[test]
fn test_nosuggest_forbid() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/suite/2_nosuggest_forbid.test");
    let mgr = TestManager::new_from_file(path);
    let dict = mgr.build_dict();
    mgr.check_all(&dict);
}

#[test]
fn test_pfxsfx_num() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/suite/1_pfxsfx_num.test");
    let mgr = TestManager::new_from_file(path);
    let dict = mgr.build_dict();
    mgr.check_all(&dict);
}

#[test]
fn test_stemming_morph() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/suite/stemming_morph.test");
    let mgr = TestManager::new_from_file(path);
    let dict = mgr.build_dict();
    mgr.check_all(&dict);
}

#[test]
fn test_pfxsfx() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/suite/1_pfxsfx.test");
    let mgr = TestManager::new_from_file(path);
    let dict = mgr.build_dict();
    mgr.check_all(&dict);
}
