name: Python Release

on:
  push:
    tags:
    - 'v*'

jobs:
  linux_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build libc wheels
      uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        # container default is manylinux
        args: --release -o dist --manifest-path crates/zspell-py/Cargo.toml
    - name: Build musl wheels
      uses: messense/maturin-action@v1
      with:
        target: x86_64-unknown-linux-musl
        manylinux: musllinux_1_1
        command: build
        args: --release -o dist -i 3.7 3.8 3.9 3.10 --manifest-path crates/zspell-py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  windows_wheels:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --manifest-path crates/zspell-py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  macos_wheels:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --universal2 --manifest-path crates/zspell-py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  release_all_wheels:
    name: Release wheels
    runs-on: ubuntu-latest
    # needs: [ linux ]
    needs: [ linux_wheels, macos_wheels, windows_wheels ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
